version: '3.1'

services:

  #### MONGODB

  #banco de dados não relacional
  mongo:
    image: mongo
    restart: always
    container_name: node_gama_conta_corrente
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 

  #interface web para administração do mongodb
  admin_mongo:
    image: mrvautin/adminmongo
    container_name: gama_admin_mongo
    restart: always
    ports:
      - 9080:1234
    environment:
      - HOST=0.0.0.0      
      - CONN_NAME=gama_mongo
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_HOST=mongo
      - DB_PORT=27017
      #- PORT=9080
      #- DB_NAME=gama_conta_corrente
    depends_on:
      - mongo

  #### POSTGRESS

  # banco de dados relacional
  postgres:
    image: postgres
    restart: always
    container_name: gama_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gama

  # interface web para administração do postgres
  admin_postgres:
    image: adminer
    container_name: gama_admin_postgres
    ports:
      - 9081:8080
    depends_on:
      - postgres
